version: '3.0'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
    - "2181:2181/tcp"
    environment:
      SERVICE_NAME: zookeeper
      SERVICE_TAGS: monitoring
    networks:
    - widget_overlay_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker3]

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
    - zookeeper
    ports:
    - "9092:9092/tcp"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ADVERTISED_HOST_NAME}:2181
      SERVICE_NAME: kafka
      SERVICE_TAGS: monitoring
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - widget_overlay_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker3]

networks:
  widget_overlay_net:
    external: true

volumes:
  widget_data_vol:
    external: true
