apiVersion: v1
kind: ConfigMap
metadata:
  name: confluent-cloud-kafka
data:
  ssl.endpoint.identification.algorithm: "https"
  sasl.mechanism: "PLAIN"
  request.timeout.ms: "20000"
  retry.backoff.ms: "500"
  security.protocol: "SASL_SSL"
