apiVersion: v1
kind: Secret
metadata:
  name: confluent-cloud-kafka
  # namespace: dev
type: Opaque
data:
  bootstrap.servers: <your_base64_encoded_secret>
  sasl.jaas.config: <your_base64_encoded_secret>
