apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas
  # namespace: dev
type: Opaque
data:
  mongodb.uri.accounts: <your_base64_encoded_secret>
  mongodb.uri.fulfillment: <your_base64_encoded_secret>
  mongodb.uri.orders: <your_base64_encoded_secret>
